import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  TablerIconCatalogItem,
  TablerIconNode,
} from "@/lib/pages/page-icon.ts";

/** Self-hosted Tabler catalog asset, generated by `scripts/sync-tabler-icons-public.mjs`. */
export const TABLER_ICONS_URL = "/tabler/icons.json";

export interface TablerIconCatalog {
  byName: Map<string, TablerIconCatalogItem>;
  list: TablerIconCatalogItem[];
}

async function fetchTablerIconCatalog(): Promise<TablerIconCatalog> {
  const response = await fetch(TABLER_ICONS_URL, { cache: "force-cache" });
  if (!response.ok) {
    throw new Error(`Failed to load Tabler icon catalog (${response.status})`);
  }
  const list = (await response.json()) as TablerIconCatalogItem[];
  const byName = new Map(list.map((item) => [item.name, item]));
  return { list, byName };
}

/**
 * Shared query for the deferred Tabler catalog. Parsed once and cached forever; reused by the
 * icon picker panel and {@link useTablerIconGlyph} so the asset is fetched at most once.
 */
export const tablerIconCatalogQueryOptions = queryOptions({
  queryKey: ["page-icon", "tabler-catalog"],
  queryFn: fetchTablerIconCatalog,
  staleTime: Number.POSITIVE_INFINITY,
  gcTime: Number.POSITIVE_INFINITY,
});

/** Loads the full catalog for the picker. `enabled` gates the fetch until the panel mounts. */
export function useTablerIconCatalog(enabled = true) {
  return useQuery({ ...tablerIconCatalogQueryOptions, enabled });
}

export interface TablerIconGlyph {
  filled: boolean;
  node: TablerIconNode;
}

/**
 * Reads a single icon's glyph from the cached catalog without triggering a fetch (`enabled: false`).
 * Returns `undefined` until the catalog is warmed, so {@link PageIconDisplay} can paint a fallback first.
 */
export function useTablerIconGlyph(name: string): TablerIconGlyph | undefined {
  const { data } = useQuery({
    ...tablerIconCatalogQueryOptions,
    enabled: false,
    select: (catalog): TablerIconGlyph | undefined => {
      const item = catalog.byName.get(name);
      return item ? { node: item.node, filled: item.filled } : undefined;
    },
  });
  return data;
}
