/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DevRouteImport } from './routes/dev'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as PSplatRouteImport } from './routes/p.$'
import { Route as DevCanvasRouteImport } from './routes/dev_.canvas'
import { Route as DbDatabaseIdRouteImport } from './routes/db.$databaseId'
import { Route as DbDatabaseIdRowIdRouteImport } from './routes/db.$databaseId.$rowId'

const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCanvasRoute = DevCanvasRouteImport.update({
  id: '/dev_/canvas',
  path: '/dev/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const DbDatabaseIdRoute = DbDatabaseIdRouteImport.update({
  id: '/db/$databaseId',
  path: '/db/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DbDatabaseIdRowIdRoute = DbDatabaseIdRowIdRouteImport.update({
  id: '/$rowId',
  path: '/$rowId',
  getParentRoute: () => DbDatabaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dev': typeof DevRoute
  '/settings': typeof SettingsRouteWithChildren
  '/template': typeof TemplateRoute
  '/db/$databaseId': typeof DbDatabaseIdRouteWithChildren
  '/dev/canvas': typeof DevCanvasRoute
  '/p/$': typeof PSplatRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
  '/db/$databaseId/$rowId': typeof DbDatabaseIdRowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dev': typeof DevRoute
  '/template': typeof TemplateRoute
  '/db/$databaseId': typeof DbDatabaseIdRouteWithChildren
  '/dev/canvas': typeof DevCanvasRoute
  '/p/$': typeof PSplatRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings': typeof SettingsIndexRoute
  '/db/$databaseId/$rowId': typeof DbDatabaseIdRowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dev': typeof DevRoute
  '/settings': typeof SettingsRouteWithChildren
  '/template': typeof TemplateRoute
  '/db/$databaseId': typeof DbDatabaseIdRouteWithChildren
  '/dev_/canvas': typeof DevCanvasRoute
  '/p/$': typeof PSplatRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
  '/db/$databaseId/$rowId': typeof DbDatabaseIdRowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dev'
    | '/settings'
    | '/template'
    | '/db/$databaseId'
    | '/dev/canvas'
    | '/p/$'
    | '/settings/$section'
    | '/settings/'
    | '/db/$databaseId/$rowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dev'
    | '/template'
    | '/db/$databaseId'
    | '/dev/canvas'
    | '/p/$'
    | '/settings/$section'
    | '/settings'
    | '/db/$databaseId/$rowId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dev'
    | '/settings'
    | '/template'
    | '/db/$databaseId'
    | '/dev_/canvas'
    | '/p/$'
    | '/settings/$section'
    | '/settings/'
    | '/db/$databaseId/$rowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DevRoute: typeof DevRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TemplateRoute: typeof TemplateRoute
  DbDatabaseIdRoute: typeof DbDatabaseIdRouteWithChildren
  DevCanvasRoute: typeof DevCanvasRoute
  PSplatRoute: typeof PSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev_/canvas': {
      id: '/dev_/canvas'
      path: '/dev/canvas'
      fullPath: '/dev/canvas'
      preLoaderRoute: typeof DevCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$databaseId': {
      id: '/db/$databaseId'
      path: '/db/$databaseId'
      fullPath: '/db/$databaseId'
      preLoaderRoute: typeof DbDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$databaseId/$rowId': {
      id: '/db/$databaseId/$rowId'
      path: '/$rowId'
      fullPath: '/db/$databaseId/$rowId'
      preLoaderRoute: typeof DbDatabaseIdRowIdRouteImport
      parentRoute: typeof DbDatabaseIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface DbDatabaseIdRouteChildren {
  DbDatabaseIdRowIdRoute: typeof DbDatabaseIdRowIdRoute
}

const DbDatabaseIdRouteChildren: DbDatabaseIdRouteChildren = {
  DbDatabaseIdRowIdRoute: DbDatabaseIdRowIdRoute,
}

const DbDatabaseIdRouteWithChildren = DbDatabaseIdRoute._addFileChildren(
  DbDatabaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DevRoute: DevRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TemplateRoute: TemplateRoute,
  DbDatabaseIdRoute: DbDatabaseIdRouteWithChildren,
  DevCanvasRoute: DevCanvasRoute,
  PSplatRoute: PSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
