import { queryOptions, useQuery } from "@tanstack/react-query";

import { getSidebarTablerGlyphs } from "@/lib/pages/get-sidebar-tabler-glyphs.ts";
import type {
  TablerIconCatalogItem,
  TablerIconNode,
} from "@/lib/pages/page-icon.ts";

/** Self-hosted Tabler catalog asset, generated by `scripts/sync-tabler-icons-public.mjs`. */
export const TABLER_ICONS_URL = "/tabler/icons.json";

export interface TablerIconCatalog {
  byName: Map<string, TablerIconCatalogItem>;
  list: TablerIconCatalogItem[];
}

async function fetchTablerIconCatalog(): Promise<TablerIconCatalog> {
  const response = await fetch(TABLER_ICONS_URL, { cache: "force-cache" });
  if (!response.ok) {
    throw new Error(`Failed to load Tabler icon catalog (${response.status})`);
  }
  const list = (await response.json()) as TablerIconCatalogItem[];
  const byName = new Map(list.map((item) => [item.name, item]));
  return { list, byName };
}

/**
 * Shared query for the deferred Tabler catalog. Parsed once and cached forever; used by the
 * icon picker panel only — passive display uses SSR glyphs or {@link tablerGlyphByNameQueryOptions}.
 */
export const tablerIconCatalogQueryOptions = queryOptions({
  queryKey: ["page-icon", "tabler-catalog"],
  queryFn: fetchTablerIconCatalog,
  staleTime: Number.POSITIVE_INFINITY,
  gcTime: Number.POSITIVE_INFINITY,
});

/** Loads the full catalog for the picker. `enabled` gates the fetch until the panel mounts. */
export function useTablerIconCatalog(enabled = true) {
  return useQuery({ ...tablerIconCatalogQueryOptions, enabled });
}

export interface TablerIconGlyph {
  filled: boolean;
  node: TablerIconNode;
}

/** Fetches a single Tabler glyph by name via the server catalog (no full JSON download). */
export function tablerGlyphByNameQueryOptions(name: string) {
  return queryOptions({
    queryKey: ["page-icon", "tabler-glyph", name] as const,
    queryFn: async (): Promise<TablerIconGlyph | undefined> => {
      const glyphs = await getSidebarTablerGlyphs({ data: [name] });
      return glyphs[name];
    },
    staleTime: Number.POSITIVE_INFINITY,
    gcTime: Number.POSITIVE_INFINITY,
  });
}

/**
 * Resolves a Tabler glyph for passive display. Prefer `preloadedGlyph` from the root loader;
 * otherwise fetches by name from the server catalog without loading the full picker asset.
 */
export function useTablerIconGlyph(
  name: string,
  enabled = true
): TablerIconGlyph | undefined {
  const { data } = useQuery({
    ...tablerGlyphByNameQueryOptions(name),
    enabled: enabled && name.length > 0,
  });
  return data;
}
